---
# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
  docker:
    - image: circleci/mysql:5.7
  working_directory: /root/singnet
  environment:
    PYTHONPATH: /root/singnet/snet-platform-usage
  steps:
    - checkout
    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "metering/requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
    - run:
        name: Install Python and Git
        command: |
          mysql --version
          service mysql start
          apt-get update
          apt-get -y install sudo wget git
          apt-get -y install python3 python3-pip
    - run:
        name: install dependencies
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r metering/requirements.txt
    - save_cache:
        paths:
          - ./venv
        key: v1-dependencies-{{ checksum "requirements.txt" }}
    # run tests!
    # this example uses Django's built-in test-runner
    # other common Python testing frameworks include pytest and nose
    # https://pytest.org
    # https://nose.readthedocs.io
    - run:
        name: run tests
        command: |
          . venv/bin/activate
          python metering/tests/test_total_calls.py test
    - store_artifacts:
        path: test-reports
        destination: test-reports
